blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/himanshu231204/AutoML-Studio-Pro-/discussions
    about: Please use Discussions for support questions and open-ended ideas.
